# Generated by Django 3.1.7 on 2021-02-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ProductoImagen',
            field=models.ImageField(default='uploads/None/no-img.jpg', upload_to='uploads/'),
        ),
    ]
