# Generated by Django 3.1.7 on 2021-02-22 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_producto_productoimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='CategoriaImagen',
            field=models.ImageField(default='uploads/None/no-img.jpg,', upload_to='uploads/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProductoCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProductoImagen',
            field=models.ImageField(default='uploads/None/no-img.jpg,', upload_to='uploads/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ProductoPrecio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
